name: Terragrunt  CI/CD

on:
    push:
        branches:
            - master

jobs:
    terragrunt:
        name: Terragrunt
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with: 
                  repository: adiallo47/terraform-modules
                  ref: "master"
            
            - name: Install Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Terraform version
              run: echo terraform --version

            - name: Install and setup Terragrunt
              run: |
                sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.38.4/terragrunt_linux_amd64"
                sudo chmod +x /bin/terragrunt
                echo terragrunt -v


            #AWS Credentials    
            - name: AWS Creds
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            
            #Terragrunt cache clear
            - name: Clear Terragrunt Cache
              run: rm -rf .terragrunt-cache

            #Run Terragrunt
            - name: Run Terragrunt
              run: |
                cd terragrunt-configs/staging/s3
                terragrunt init
                terragrunt plan
            
            - name: Apply Terragrunt Changes
              if: github.ref == 'refs/heads/main'
              run: |
                cd terragrunt-configs/staging/s3
                terragrunt apply -auto-approve